env:
  browser: true
  es2020: true
  node: true
extends:
  - standard
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - "plugin:@typescript-eslint/recommended"
ignorePatterns:
  - lib/**/*
  - build/**/*
  - dist/**/*
  - package-lock.json
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - prettier
  - "@typescript-eslint"
  - sort-keys-fix
  - simple-import-sort
  - unused-imports
settings:
  react:
    version: detect
parser: "@typescript-eslint/parser"
rules:
  "@typescript-eslint/no-explicit-any": warn
  no-console: warn
  prettier/prettier: warn
  sort-vars: warn
  "@typescript-eslint/member-ordering":
    [warn, { default: { order: alphabetically } }]
  sort-keys-fix/sort-keys-fix: warn
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
  "@typescript-eslint/no-unused-vars": off
  unused-imports/no-unused-imports: warn
  unused-imports/no-unused-vars: [
			warn,
			{ "vars": "all", "varsIgnorePattern": "^_", "args": "after-used", "argsIgnorePattern": "^_" }
  ]
