version: '3.8'

services:
  protofun-service:
    image: protofun-service
    ports:
      - "3030:3030"
    environment:
      VIRTUAL_HOST: service.protocol.fun
      VIRTUAL_PORT: 3030
      LETSENCRYPT_HOST: service.protocol.fun
      LETSENCRYPT_EMAIL: hello@danielconstantin.net
    networks:
      - graph-node_proxy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    environment:
      PGWEB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5433/${POSTGRES_DB}?sslmode=disable
    ports:
      - "8082:8081"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  graph-node_proxy:
    external: true
